export const SUPA_URL = 'https://unzcjivqyicfpkhyzxcf.supabase.co';
export const SUPA_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuemNqaXZxeWljZnBraHl6eGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NjczMDIsImV4cCI6MjA4ODI0MzMwMn0.i3dn3XH0f1H4P6_d2ELlec0_AuOaMgQ_yYJlb-6XSOM';
